#!/bin/bash -l
#PBS -N rfd3
#PBS -A FRAME-IDP
#PBS -q debug
#PBS -l select=1
#PBS -l walltime=00:20:00
#PBS -l filesystems=home:eagle
#PBS -j oe
#PBS -o rfd3_single_node.log

cd "$PBS_O_WORKDIR"                

# your setup (modules/env)
module use /soft/modulefiles
module load conda/2025-09-25
conda activate rfd3

# run your program
torchrun --nproc_per_node=4 examples/enzyme_multinode.py --n_batches 1 --diffusion_batch_size 4 --seqs_per_backbone 1 --output_dir /home/raswanth/foundry/enzyme_output --theozyme theozymes/00A0M0R-theozyme.pdb --spec 00a0m0r

