#!/bin/bash -l
#PBS -N rfd3
#PBS -A FRAME-IDP
#PBS -q prod
#PBS -l select=60
#PBS -l walltime=02:00:00
#PBS -l filesystems=home:eagle
#PBS -j oe
#PBS -o rfd3_multi_node_array.log
#PBS -J 0-9
#PBS -r y

cd "$PBS_O_WORKDIR"
set -euo pipefail
module use /soft/modulefiles
module load conda/2025-09-25
conda activate rfd3

THEOZYMES=(
    "theozymes/000CW0W-theozyme.pdb"
    "theozymes/00A0M0R-theozyme.pdb"
    "theozymes/00M0I0R-theozyme.pdb"
    "theozymes/00Y0LFH-theozyme.pdb"
    "theozymes/0H00Q0R-theozyme.pdb"
    "theozymes/0K0000W-theozyme.pdb"
    "theozymes/0T0000Y-theozyme.pdb"
    "theozymes/FNG00TF-theozyme.pdb"
    "theozymes/LD00R0W-theozyme.pdb"
    "theozymes/NK0GN0W-theozyme.pdb"
    "theozymes/TFM0WHS-theozyme.pdb"
    "theozymes/TTLAF0P-theozyme.pdb"
)

SPECS=(
    "000cw0w"
    "00a0m0r"
    "00m0i0r"
    "00y0lfh"
    "0h00q0r"
    "0k0000w"
    "0t0000y"
    "fng00tf"
    "ld00r0w"
    "nk0gn0w"
    "tfm0whs"
    "ttlaf0p"
)

IDX=${PBS_ARRAY_INDEX}
THEOZYME=${THEOZYMES[$IDX]}
SPEC=${SPECS[$IDX]}

TORCHRUN=$(command -v torchrun)
NNODES=$(wc -l < "$PBS_NODEFILE")
MASTER_ADDR=$(head -n 1 "$PBS_NODEFILE")
MASTER_PORT=${MASTER_PORT:-29500}
export TORCHRUN NNODES MASTER_ADDR MASTER_PORT
BASE_OUT=${BASE_OUT:-/lus/grand/projects/FRAME-IDP/raswanth/enzyme_output_multi_node_2/${SPEC}}
SEED_BASE=${SEED_BASE:-0}
export BASE_OUT SEED_BASE

cd "$PBS_O_WORKDIR"
mpiexec --envall --cpu-bind=none -np "$NNODES" -ppn 1 -hostfile "$PBS_NODEFILE" bash -lc '
  set -euo pipefail
  NODE_RANK=${PMI_RANK:-${OMPI_COMM_WORLD_RANK:-0}}
  SEED=$((SEED_BASE + NODE_RANK))
  '"$TORCHRUN"' --nnodes='"$NNODES"' --nproc_per_node=4 --rdzv_backend=c10d --rdzv_endpoint='"$MASTER_ADDR:$MASTER_PORT"' --node_rank="$NODE_RANK" \
    examples/enzyme_multinode.py \
      --output_dir "$BASE_OUT" \
      --n_batches 120 \
      --diffusion_batch_size 20 \
      --seqs_per_backbone 5 \
      --theozyme '"$THEOZYME"' \
      --spec '"$SPEC"' \
      --seed "$SEED"
'
